Repository zimmerman-team/Dx.server, pull requests merged in 2024-07, with the labels that each got.

#53 feat: The All tab should reflect the same ‘last updated’ state as the…
  src/controllers/assets.controller.ts
Labels: size/XS

#51 chore: update path for winston logger
  src/config/logger/winston-logger.ts
  src/utils/renderChart/winston-logger.js
Labels: size/XS

#50 feat:DX-1543; add heading field to report model
  src/controllers/assets.controller.ts
  src/controllers/reports.controller.ts
  src/controllers/user.controller.ts
  src/models/report.model.ts
Labels: size/S

#54 Revert "feat:DX-1543; add heading field to report model"
  src/controllers/assets.controller.ts
  src/controllers/reports.controller.ts
  src/controllers/user.controller.ts
  src/models/report.model.ts
Labels: size/S

#56 feat: DX-1601 - Stacked BarChart Implementation, DX-1600 - Multi-set …
  src/utils/renderChart/index.js
Labels: size/M

#57 feat: make dataset source url not compulsory field
  src/models/dataset.model.ts
Labels: size/XS

#58 feat: DX-1486 - show only datasets owned by user
  src/controllers/dataset.controller.ts
Labels: size/S
