Repository zimmerman-team/Dx.server, pull requests merged in 2024-08, with the labels that each got.

#59 Feat/dx 1608
  src/controllers/dataset.controller.ts
Labels: size/XS

#60 fix: Fix sortby query
  src/controllers/dataset.controller.ts
Labels: size/XS

#62 Feat/dx 1770
  src/controllers/user.controller.ts
Labels: size/S

#61 Feat/dx 1159
  src/controllers/charts.controller.ts
  src/controllers/dataset.controller.ts
  src/controllers/file-upload.controller.ts
  src/controllers/reports.controller.ts
  src/controllers/user.controller.ts
  src/utils/planAccess.ts
Labels: size/L
