Repository zimmerman-team/Dx.server, pull requests merged in 2024-05, with the labels that each got.

#39 feat: DX-1417 - Tag for Intercom
  src/controllers/user.controller.ts
Labels: size/S

#38 feat: DX-1227 - Implement the Delete Account Flow as per design
  src/authentication-strategies/user-profile.ts
  src/controllers/user.controller.ts
Labels: size/M

#40 fix;DX-1426:adjust dataset filter logic
  src/utils/renderChart/index.js
Labels: size/XS

#41 feat: Complete Linkedin Campaign flow
  package.json
  src/controllers/charts.controller.ts
  src/controllers/reports.controller.ts
  src/controllers/user.controller.ts
  yarn.lock
Labels: size/L

#42 feat: update caching code for organisation check
  src/utils/auth.ts
Labels: size/M

#43 chore: add log
  src/utils/auth.ts
Labels: size/XS
