Repository zimmerman-team/Dx.server, pull requests merged in 2024-03, with the labels that each got.

#24 feat: added a data creator id for creating public assets
  src/controllers/charts.controller.ts
  src/controllers/dataset.controller.ts
  src/controllers/reports.controller.ts
Labels: size/M

#27 DX-1129: Create Organisation Zimmerman on Auth0
  src/authentication-strategies/user-profile.ts
  src/controllers/charts.controller.ts
  src/controllers/dataset.controller.ts
  src/controllers/reports.controller.ts
  src/utils/auth.ts
Labels: size/L

#26 Feat/dx 1128
  src/controllers/charts.controller.ts
  src/utils/renderChart/index.js
Labels: size/S

#28 fix: fixed issues with normal user accesss
  src/controllers/charts.controller.ts
  src/controllers/dataset.controller.ts
  src/controllers/reports.controller.ts
  src/utils/auth.ts
Labels: size/M
