Repository zimmerman-team/Dx.server, pull requests merged in 2025-03, with the labels that each got.

#85 fix: enhance duplicate name functionality for charts, datasets, and stories
  src/controllers/charts.controller.ts
  src/controllers/dataset.controller.ts
  src/controllers/stories.controller.ts
  src/utils/duplicateName.ts
Labels: size/M

#84 feat: DX-2281 - Cache not enforcing org asset check
  src/controllers/charts.controller.ts
  src/controllers/dataset.controller.ts
  src/controllers/stories.controller.ts
  src/interceptors/cache.interceptor.ts
  src/utils/redis.ts
Labels: size/M

#83 feat: DX-2271 - Logic implementation Asset Owner on Card
  src/authentication-strategies/user-profile.ts
  src/controllers/assets.controller.ts
  src/controllers/charts.controller.ts
  src/controllers/dataset.controller.ts
  src/controllers/stories.controller.ts
  src/controllers/user.controller.ts
  src/interceptors/cache.interceptor.ts
  src/utils/auth.ts
  src/utils/redis.ts
Labels: size/L

#86 feat: Pricing active check
  src/controllers/user.controller.ts
Labels: size/XS
